### ISSUE TITLE
Setup calls for pytest, but test folder doesn't appear to have runnable tests

### ISSUE THREAD

**Issue by rveeblefetzer** [tbekolay/ti#15]
I'm unaware of how these tests are run. I see setup.cfg calling for pytest, but I don't see tests in a unittest/pytest syntax. I tried looking up bash tests, in case these are somehow usable too, but can't figure it out. Any help?

**Comment by tbekolay** [comment]
If you look at setup.py, you'll see that the [tests require](https://github.com/tbekolay/ti/blob/master/setup.py#L38) [pytest-cram](https://github.com/tbekolay/pytest-cram), which runs the tests with [cram](https://bitheap.org/cram/) through pytest.

I haven't updated pytest-cram in some time, so it's possible that there may be issues with more recent version of pytest; if you find any, please open an [issue](https://github.com/tbekolay/pytest-cram/issues) there. Thanks!

**Comment by rveeblefetzer** [comment]
Checking it out. Thanks!
