### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by ghost** [tbekolay/ti#21]
Is this project still active?

**Comment by tbekolay** [comment]
I don't have any plans to do work on `ti` in the near future. If anyone wants to take over maintenance, I would be happy to transfer the repository.

**Comment by richmeta** [comment]
Hi @tbekolay, 

I cloned this project a while back and implemented a few updates. So i know the code pretty well. I'd be happy to take over maintenance of this project if that's ok with you.

**Comment by tbekolay** [comment]
@richardfrenchuk Sounds good to me! I'll transfer this repository to you. If you let me know your PyPI username, I'll transfer the PyPI project over to you as well.

**Comment by richmeta** [comment]
thanks @tbekolay,  my pypi username is richardf

**Comment by tbekolay** [comment]
Great, I've added you as an owner on PyPI. I don't see a way to remove myself as an owner, but if you have a way to do that feel free.
