### ISSUE TITLE
Documentation could be updated

### ISSUE THREAD

**Issue by benjaminwil** [tbekolay/ti#8]
The `ti` repo at [sharat87/ti](https://github.com/sharat87/ti) links to this fork, as development has moved here. However, all of the links in this fork's readme link back to the inactive repo. Additionally, the main website is still live at [ti.sharats.me](http://ti.sharats.me) and links to @sharat87's original repo. 

I'm happy to commit these simple changes, but I'm wondering if I can contribute any other housekeeping documentation changes while I'm at it?

**Comment by rveeblefetzer** [comment]
@benjaminwil you still want to do this? It should happen. I can get in there, but if you're keen go for it

**Comment by benjaminwil** [comment]
I'm happy to change the links over! I may not have enough time to make other meaningful changes right now, though.

**Comment by benjaminwil** [comment]
- Looks like issues #6 and #12 are also documentation requests.
- Also, I am not able to change the repo's description, which includes a link to [ti.sharats.me](http://ti.sharats.me) – I think @tbekolay needs to make that change (if it's necessary).

**Comment by tbekolay** [comment]
Once the docs live somewhere else (readthedocs or github pages) I can update it.

**Comment by benjaminwil** [comment]
Thanks @tbekolay. I just submitted pull request #14 with some minor changes to the readme. Mostly just changing the links to the source and GitHub issues page to reference `tbekolay/ti` instead of `sharat87/ti`.

**Comment by tbekolay** [comment]
Thanks for the PR; I updated the link in the description. More documentation work would be great of course, but since there are other issues for it I'm going to consider #14 a fix for this issue and close it.
